import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import img1 from '../assets/img1.png';
import img2 from '../assets/img2.png';
import img3 from '../assets/img3.png';
import img5 from '../assets/img5.png';
import img7 from '../assets/img7.png';
import img9 from '../assets/img9.png';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container-fluid">
        <div className="row">
          <div className="col">
            Back
          </div>
          <div className="col">
            <div className="row">
              Digital Artist
            </div>
            <div className="row">
              BANKSY_IS_DEAD
            </div>
          </div>
          <div className="col">
            Menu
          </div>
        </div>

        <div className="row">
          <div className="col-md-2">
            <div>
              <Image src={img1} alt="testing" style={{ width: '100%', height: 'auto' }} />
            </div>
            <div>
              Testing
            </div>
            <div>
              22,600
            </div>
          </div>
          <div className="col-md-2">
            <div>
              <Image src={img2} alt="testing" style={{ width: '100%', height: 'auto' }} />
            </div>
            <div class="row">
              <div class="col">
                Testing
              </div>
              <div class="col">
                7,850
              </div>
            </div>
          </div>
          <div className="col-md-2">
            <div>
              <Image src={img3} alt="testing" style={{ width: '100%', height: 'auto' }} />
            </div>
            <div class="row">
              <div class="col">
                Testing
              </div>
              <div class="col">
                10,330
              </div>
            </div>
          </div>
          <div className="col-md-2">
            <div>
              <Image src={img7} alt="testing" style={{ width: '100%', height: 'auto' }} />
            </div>
            <div class="row">
              <div class="col">
                Testing
              </div>
              <div class="col">
                2,150
              </div>
            </div>
          </div>
          <div className="col-md-2">
            <div>
              <Image src={img5} alt="testing" style={{ width: '100%', height: 'auto' }} />
            </div>
            <div class="row">
              <div class="col">
                Testing
              </div>
              <div class="col">
                2,150
              </div>
            </div>
          </div>
        </div>

        <div className="row">
          <div className="col">
            <div className="row">CHILDREN OF</div>
            <div className="row">FORGOTTEN</div>
            <div className="row">GOD</div>
          </div>
          <div className="col">EXPLORE MORE ARTWORKS</div>
          <div className="col">START BIDDING</div>
        </div>

        <div className="row justify-content-center text-center">
          <div className="col">
            Pellentesque...
          </div>
        </div>

        <div className="row justify-content-center text-center">
          <div className="col">
            Eget quis...
          </div>
        </div>

        <div className="row">
          <div className="col">
            <Image src={img1} alt="testing" style={{ width: '100%', height: 'auto' }} />
          </div>
          <div className="col">
            <Image src={img1} alt="testing" style={{ width: '100%', height: 'auto' }} />
          </div>
          <div className="col">
            <Image src={img1} alt="testing" style={{ width: '100%', height: 'auto' }} />
          </div>
        </div>

        <div className="row">
          <div className="col">
            <div className="row">Odio morbi</div>
            <div className="row">Sed nunc nunc sagittis</div>
          </div>
          <div className="col">
            <Image src={img9} alt="testing" style={{ width: '100%', height: 'auto' }} />
          </div>
        </div>
      </main>
    </>
  )
}
